### ISSUE TITLE
TBD Field Collection Re-Import Bug

### ISSUE THREAD

**Issue by iamEAP** [tableau-mkt-archived/entity_xliff#101]
There appears to be a bug in the way content is re-imported when it contains field collections.

Here's repro: https://travis-ci.org/tableau-mkt/entity_xliff/builds/105820068 (104f061)

**Comment by iamEAP** [comment]
This may or may not be related to strangeness that crops up as a result of running both Entity Field translation and Content Translation on the same Drupal install...

**Comment by pvanoverbeek** [comment]
now impacting TCOT translations

**Comment by pvanoverbeek** [comment]
Closing - 3/23 ticket cleaning review
