### ISSUE TITLE
Support exporting most current workbench moderation revision

### ISSUE THREAD

**Issue by iamEAP** [tableau-mkt-archived/entity_xliff#115]
Per #112 and #114...  We need a to add support for exporting the most current workbench moderation revision without breaking imports.

**Comment by pvanoverbeek** [comment]
@iamEAP - Doing some house cleaning here. What is the status of this one? Still working or can it be closed out?

**Comment by iamEAP** [comment]
Fixed downstream in our site, but still needs to be ported back into this repo. Believe that's in progress, @jkopel?

**Comment by jkopel** [comment]
Yes this is fixed on WWW and it might be here as well. I am not really sure of the status for this specific issue.
