### ISSUE TITLE
Allow Link field href to be exported/imported

### ISSUE THREAD

**Issue by iamEAP** [tableau-mkt-archived/entity_xliff#118]
In the spirit of "shrinkwrap the whole entity" it makes sense to include the "href" attribute of the Link field (from Link module) to be included in XLIFF exports/imports.

This allows scenarios where translators have been directed to manually alter links during translation (or for upstream systems to filter out the href if so desired).

**Comment by iamEAP** [comment]
Should be a quick update to this file (plus tests): https://github.com/tableau-mkt/entity_xliff/blob/7.x-1.x/src/Drupal/FieldHandlers/LinkFieldHandler.php

also related to www7 #3584

**Comment by dsullivantableau** [comment]
Can we escalate this to high?

**Comment by jkopel** [comment]
Fixed in #139
