### ISSUE TITLE
Add functionality to translate 'Summary' on a 'Body'-field

### ISSUE THREAD

**Issue by MichaelSoe** [tableau-mkt-archived/entity_xliff#126]
When exporting a node to a XLIFF-file, the 'summary' of the 'body'-field is not added to the XLIFF-file and can therefore not be translated.

Please add the functionality that exports and imports the 'summary' of the 'body'-field.

**Comment by iamEAP** [comment]
Thanks for the report @MichaelSoe!  Interesting that this isn't working, as this was a consideration from the outset. See: https://github.com/tableau-mkt/entity_xliff/blob/7.x-1.x/src/Drupal/FieldHandlers/SummarizedFieldHandler.php

The bug must be in the field mediator, perhaps here: https://github.com/tableau-mkt/entity_xliff/blob/7.x-1.x/src/Drupal/Mediator/FieldMediator.php#L95

**Comment by iamEAP** [comment]
@angrytoast Will the fixes you're working on right now address this issue as well?

**Comment by jkopel** [comment]
I think this is fixed with #118
