### ISSUE TITLE
L10N: D8 and XLIFF 2.X support

### ISSUE THREAD

**Issue by pvanoverbeek** [tableau-mkt-archived/entity_xliff#130]
@tableau-mkt-bot commented on [Wed Mar 08 2017](https://github.com/tableau-mkt/www7/issues/4773)

Does Drupal 8.X support XLIFF 2.X? 
https://www.drupal.org/node/2838786

This is research heavy, which I am only starting now.  For the time being, I want to make sure this is assigned to the new D8 Epic, which I understand is turning into one of our most active spaces in GitHub.  Fantastic!

The XLIFF Technical Committee is currently at work on XLIFF 2.0. Much feedback has been gathered from XLIFF's user community which will be synthesized and implemented into the next version of the standard. Two of the primary methods include compiling a list of extensions used by XLIFF toolmakers, and compiling a list of XLIFF features supported in each XLIFF tool. 

Makers of XLIFF tools have taken advantage of XLIFF's extensibility mechanism in order to implement a number of features. By collecting a list of these extension points, and analyzing them for common tasks, the XLIFF TC hopes to improve the XLIFF 2.0 Specification to include mechanisms that will enable the toolmakers to support these features without using extensibility. 

Makers of XLIFF tools have supported different sets of features in the XLIFF 1.2 Specification. By compiling a list of these features the XLIFF TC hopes to identify areas where the XLIFF 2.0 Specification can be improved to enable toolmakers to more widely support the specification. 

On May 6, 2014, the XLIFF 2.0 specification was moved[5] to Candidate OASIS Standard.

On August 6, 2014 the XLIFF 2.0 specification became an OASIS Standard

XLIFF 2.1
http://docs.oasis-open.org/xliff/xliff-core/v2.1/csprd01/xliff-core-v2.1-csprd01.html

https://en.wikipedia.org/wiki/XLIFF#XLIFF_2.0 
http://info.moravia.com/blog/bid/354057/What-s-So-Sexy-About-XLIFF-2-0 
http://docs.oasis-open.org/xliff/xliff-core/v2.0/os/xliff-core-v2.0-os.html 
https://www.w3.org/International/its/wiki/XLIFF_2.0_Mapping 
https://github.com/Microsoft/XLIFF2-Object-Model 
http://xmlpress.net/publications/xliff/examples/Less

>__&lt;META&gt;__
>__Daniel Sullivan__ submitted this issue on __Wed Mar 08 2017 16:56:00 GMT+0000 (UTC)__
>
>__Problem / Request Statement:__ null
>__Completion Criteria:__ Review documentation and decide if we want to go 2.X route for file processing.
>__Url - Page Affected:__ undefined
>__L.O.V:__ 5
>__Requested Completion Date:__ 2017-07-31
>__Original Ticket:__ [Workfront]( https://tableau.attask-ondemand.com/issue/view?ID=58c037cf007244cbf79d0a05dd454c4b )

---

@pvanoverbeek commented on [Thu Mar 09 2017](https://github.com/tableau-mkt/www7/issues/4773#issuecomment-285483735)

"this is not even a real ticket" - anonymous (but real)

**Comment by dsullivantableau** [comment]
Eric, is this the right place for this?  Where would you like update to XLIFF 2.x to live? @iamEAP

**Comment by iamEAP** [comment]
I'm taking this ticket to mean that you're requesting that the D8 port of Entity XLIFF use XLIFF 2.x rather than 1.2, right?

**Comment by dsullivantableau** [comment]
I spent so much time on link farming that I forgot that part.  I think we need at least to have this on the table as an option, before things really get moving with D8.  I need to investigate if this is the right direction for my part, and would need someone on the dev side to do the same from a technical standpoint.  From what I can find, XLIFF 2.X is not supported anywhere in Drupal yet.

**Comment by dsullivantableau** [comment]
Also, this is not a priority right now at all, but I wanted to make sure we had a ticket for it.  I will update this with my findings as I wade through the docs.

**Comment by iamEAP** [comment]
When we port to D8, we'll probably want to use the [Serialization API](https://www.drupal.org/docs/8/api/serialization-api/serialization-api-overview) and provide our own custom XLIFF encoder(?)  One option.

**Comment by dsullivantableau** [comment]
Good to know.  Thank you, Eric.  More homework for me.  I will go through this and swing back with questions.

**Comment by violalee** [comment]
Closing this in 8/28 in ticket clean-up session with Eric.
