### ISSUE TITLE
Add Entity Translation support for Field Collections

### ISSUE THREAD

**Issue by iamEAP** [tableau-mkt-archived/entity_xliff#21]
Work on this issue is blocked by official Entity Translation support in Field Collection. See: https://www.drupal.org/node/1344672?

**Comment by pvanoverbeek** [comment]
@iamEAP is this still legit. We want to kill if not needed.

**Comment by iamEAP** [comment]
@pvanoverbeek It is legit for the community, but not important to us currently.

**Comment by pvanoverbeek** [comment]
closing, Drupal folks unite!
